// This is used to make connecting to MongoDB easier
const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const exerciseSchema = new Schema({
	username: {
		type: String,
		required: true
	},
	description: {
		type: String,
		required: true
	},
	duration: {
		type: Number,
		required: true
	},
	date: {
		type: Date,
		required: true
	}
	/* the ','s are required on all members of the JSON or JavaScript object 
	 * except the last.
	 */
}, {
	// Timestamps are automatically generated by MongoDB
	timestamps: true
});

/* Does MongoDB copy the name from here, lower-case it and add an 's' to 
 * create the database collection name?
 */
const Exercise = mongoose.model('Exercise', exerciseSchema);
/* This is used by the router to validate and create the objects to store on 
 * the database.
 */
module.exports =  Exercise;
